name: melodia
services:
  backend:
    container_name: backend
    image: backend:latest
    env_file:
      - .env
    ports:
      - "${BACKEND_EXPOSED_PORT:-5000}:${BACKEND_DOCKER_PORT:-5000}"
    networks:
      - testing_net
  

    


networks:
  testing_net:
    external: true
